language: ruby
cache: bundler
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx
  - rbx-2
gemfile:
  - gemfiles/rollbar-1.x.gemfile
  - gemfiles/rollbar-2.x.gemfile
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: rbx-2
  fast_finish: true
before_install:
  - gem install bundler
sudo: false
