language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx
gemfile:
  - gemfiles/rollbar-1.2.x.gemfile
matrix:
  allow_failures:
    - rvm: rbx
  fast_finish: true
